### ISSUE TITLE
how to start

### ISSUE THREAD

**Issue by mvolkmann** [nathanfarlow/PineappleCAS#17]
I have installed clibs.8xg and PCAS.8xp on my TI-84 Plus CE. The instructions say "If you have CE OS 5.3 or higher, simply execute prgmPCAS on the calculator." I have CE OS 5.4. I press prgm, select PCAS, and press enter. The screen says "prgmPCAS". I press enter again and it says "ERROR: MEMORY" and "Memory is insufficient to perform the calculation. Check infinite recursions or loops."

Am I missing a step?

**Comment by jaymnorth** [comment]
I am having the same problem and could really benefit from this on an upcoming exam! Please help :,(

**Comment by jaymnorth** [comment]
I am not too sure how but I got the program archived and now it works like a charm! This is great

**Comment by nathanfarlow** [comment]
Take a look at issues #13 #14 or #15 and see if the steps solve your issue. The solution should be to archive the program as @jaymnorth did.

**Comment by mvolkmann** [comment]
I archived the PCAS program. Now when I press prgm I see that PCAS has a * in front of it. I suppose that indicates that it is archived. When I select it, I see "prgmPCAS" in the display. I press enter to execute it and still get "Memory is insufficient ...". Is there something more I'm supposed to do in addition to archivig PCAS?

**Comment by nathanfarlow** [comment]
It looks like you've successfully archived PCAS. (Although I wonder if sending to RAM then archiving on calculator has different results then sending to the calculator archive directly through TI Connect CE?) Based on comments from #8, try archiving programs you don't want to lose and then reset the RAM of the calculator by pressing reset button on the back for 2 seconds. Also make sure you've archived all the clibs according to https://github.com/nathanfarlow/PineappleCAS/issues/13#issuecomment-563061454. Let me know how this works out for you so I might be able to update the readme because this is a common issue.

**Comment by mvolkmann** [comment]
Archiving all my programs enabled PCAS to work! I did not do anything to archive the clibs. #13 doesn't seem to address that and I don't know how to archive a library, only programs. I only had three programs installed: PACMAN, PCAS, and TETRICA.

**Comment by nathanfarlow** [comment]
Glad it's working! Thanks for the report back on what worked.
