### ISSUE TITLE
Better Testing

### ISSUE THREAD

**Issue by nathanfarlow** [nathanfarlow/PineappleCAS#2]
What is the best solution to display whether or not expressions were simplified/derived correctly? How could I integrate this into travis? @adriweb

**Comment by adriweb** [comment]
You can add a test suite to your code so that given an input; you compare the output with the known correct result (for example in a string representation, for easy writing/reading) :)
Then a good idea would be to add a "test" rule to the pc makefile so that Travis can launch it. It would run all the tests and print an error message on failure, for instance (expected: ... got: ...)

Need more (specific) help?
I haven't looked at this updated version, but I may be able to do so this weekend :)

**Comment by nathanfarlow** [comment]
Makes sense! I will implement that.

**Comment by Trajectory989** [comment]
I'm sorry to be that dumb guy but I am brand new to the scene of adding programs to a calculator and such. Literally, I just want a program for the ti-84 plus ce that, like the derivative function of a ti-89, will output an actual equation unlike the nDeriv function that is currently implemented. I heard of the program symbolic only to realize it only works on ti-83+ calculators. So I'm here. You seem to be (at least pretty recently) a developer of what I am talking about, but you have two different projects working towards the same goal if I am reading these things correctly. Which one should I use (the Pinapple CAS or the SymbolicDerivative) and how do i install it on my calculator?

**Comment by nathanfarlow** [comment]
Welcome to the scene! What you are looking for is the [SymbolicDerivative project](https://github.com/nathanfarlow/SymbolicDerivative) (well for now at least). Navigate to the bin folder and download DERIV.8xp. Send that to your calculator along with the [CE C Libraries](https://github.com/CE-Programming/libraries/releases/latest). Type your equation in Y1, run the DERIV program, and the derivative will be in Y2. If your OS is not the latest, you might have to run with Asm(prgmDERIV) which you can find in the catalog menu. Eventually, this project, PineappleCAS, will do everything SymbolicDerivative does but better. SymbolicDerivative does not simplify well and crashes when it runs out of memory. I am still working on PineappleCAS, I swear! School has just been very busy lately. :)

**Comment by Trajectory989** [comment]
By all means take your time. This certainly is a busy time of year. I did have to run it using asm so i should figure a way of updating I guess, but otherwise it works as you described. I do think I ought to mention this from a client side perspective though: in your PineappleCAS it may be more beneficial to have the input and outputs as variables other than Y1 and Y2. I say this because i mean to write a simple program of my own that will be utilizing yours in order to find dy/dx of a polar coordinate (obviously nothing more than a plug n' chug sort of program) but the storage of these values at Y1 and Y2 would mean any lines I currently have saved I will have to temporarily move and then replace as a part of my program. As Something to build off of and expand, I think it would be beneficial to write it like that. Of course, I still severely thank you for the work that you have done for this and your quick reply to my last comment. Best of luck in your future endeavors.

**Comment by Decimation** [comment]
Is this project still in development? I just tried to compile it but I'm getting this error:
`C:\CEDEV\INCLUDE\TICE.H (482,34) :      ERROR (121) Illegal declaration specifier`
`C:\CEDEV\INCLUDE\TICE.H (482,34) :      ERROR (177) Type specifier cannot have both "unsigned" and "signed"`

This program is exactly what I've been looking for. I was about to write a CAS myself! So if I could get this to compile it'd be amazing.

**Comment by nathanfarlow** [comment]
This project is still in development! Like I said before though, school is very busy right now. I will most likely resume this project this summer or after finals and other tests are done. I can't tell too much what's going on with the compilation issue from the lines that you gave me; make sure you have properly set up your CE build environment. Please feel free to open a new issue with all the information you can! When I resume work on this project I will make some build instructions. I would be happy to help you individually until then.

**Comment by nathanfarlow** [comment]
Hey @Decimation I fixed the compilation error. Turns out it I wasn't using the latest CE SDK. Everything should compile now!

**Comment by Decimation** [comment]
I can confirm it works! However, does the CAS simplifier not support multi-variable expressions? When I put 6xy+4xy in Y1 and run PCAS, it gives me (x * 2 + 10) * Y.

**Comment by nathanfarlow** [comment]
Yep, the simplification is pretty jank still. Let's talk about all this on the new issue: https://github.com/nathanfarlow/PineappleCAS/issues/3

**Comment by nathanfarlow** [comment]
Fixed in commit 08661aad5909e016dae9e9390d4c60c3742cbc92. Travis automatically runs the tests nicely like I had hoped. I was able to re-purpose the parser that parses ti variables to also parse normal strings without much modification. Ironically I found a ton of bugs that I fixed when I was implementing the test framework so it took some time to get those ~40 tests to all pass :smile: 

The tests are located at [tests.txt](https://github.com/nathanfarlow/PineappleCAS/blob/master/tests.txt)

(Huge thanks to @adriweb!)
