### ISSUE TITLE
Crashes when i do a simplification problem.

### ISSUE THREAD

**Issue by clayfurd** [nathanfarlow/PineappleCAS#21]
Everytime i type in the problem (10m^3+20m^2)/(15m^3+15m^2-30m) i input it as a simplification problem in y1 and i go to the UI and click simplify and my ti84ce freezes and i cant even quit the program, i have to remove the battery. Please help!

**Comment by nathanfarlow** [comment]
On the CEmu emulator, I typed in your expression and let it simplify with only "Basic Identities" checked because there is no trig or complex numbers. At 200% emulation speed, it simplified the answer in 6 minutes. Therefore on a normal calculator this computation would terminate within 12 minutes. Note that from the readme: "More likely is that an input is too difficult for PCAS, and it will take too long for PCAS to terminate, necessitating a manual RAM reset on the back of the calculator". In other words, this expression does not crash the program, but it is difficult and takes a long time to complete. You can either wait for 12 minutes for it to terminate, or as you have mentioned, reset the calculator by pushing the reset button on the back or by removing the battery. This is because the processor on these calculators is slow and this program is not very well optimized.
