### ISSUE TITLE
Support for complex numbers

### ISSUE THREAD

**Issue by adriweb** [nathanfarlow/PineappleCAS#6]
I'm making this issue as I've seen requests for it on TI-Planet.

Well, I know this is a rather large topic, but it would be a great addition :D

Note that the complex 𝑖 would also need to behave as a "symbol" to simplify coefficients around, which is what even standard calcs do (2+3+3i-5i => 5-2i)

Thanks a good luck :)

**Comment by nathanfarlow** [comment]
Great idea. I believe this can be implemented fairly easily. (phew 😌). I'll add it in here soon.

**Comment by nathanfarlow** [comment]
I'm making some good progress on the complex branch. The CAS is really coming together!

![euleridentity](https://user-images.githubusercontent.com/22306467/60543322-ae722d80-9cdb-11e9-8e0e-eb1388e1238a.png)
![ln](https://user-images.githubusercontent.com/22306467/60543332-b3cf7800-9cdb-11e9-9909-1a94e87aa308.png)
![sin](https://user-images.githubusercontent.com/22306467/60543337-b5993b80-9cdb-11e9-97f4-adf4c42b47be.png)
![powers](https://user-images.githubusercontent.com/22306467/60543344-b762ff00-9cdb-11e9-9ccb-fb9abdd0b281.png)

**Comment by nathanfarlow** [comment]
Complex numbers are now fully supported with the latest commit. You can do really cool things with them such as 
![i^i](https://user-images.githubusercontent.com/22306467/60564002-a63de080-9d23-11e9-9a30-bd8affa566d4.png)
The engine runs this expression through several identities to evaluate the final answer. Not-so-fun-fact: Evaluating i^(5i) on the CE takes 45 seconds using full simplification in its current state. Hopefully we can somehow precompile the identities to make it faster because that process is what takes the most amount of time.

**Comment by adriweb** [comment]
Great job!
